import { StyleSheet } from "react-native";
import { theme } from "../ui/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: 20, gap: 14, paddingBottom: 40 },
  title: { fontSize: 22, fontWeight: "700", color: theme.colors.text, marginTop: 12 },
  helper: { color: theme.colors.muted, fontSize: 13, lineHeight: 19 },
  voiceHint: { color: "#8a6d3b", fontSize: 12, lineHeight: 17 },
  tabRow: { flexDirection: "row", gap: 10 },
  tabBtn: { flex: 1, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, alignItems: "center", backgroundColor: theme.colors.panel },
  tabBtnActive: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
  tabBtnText: { color: theme.colors.muted, fontWeight: "700", fontSize: 13 },
  tabBtnTextActive: { color: "#fff" },
  levelRow: { flexDirection: "row", gap: 8 },
  levelBtn: { flex: 1, paddingVertical: 7, borderRadius: 20, borderWidth: 1, borderColor: theme.colors.border, alignItems: "center", backgroundColor: theme.colors.panel },
  levelBtnActive: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
  levelBtnText: { color: theme.colors.muted, fontSize: 13, fontWeight: "600" },
  levelBtnTextActive: { color: "#fff" },
  phraseCard: { backgroundColor: theme.colors.panel, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border, padding: 14, gap: 8 },
  phraseLabel: { color: theme.colors.muted, fontSize: 12 },
  phraseText: { color: theme.colors.text, fontSize: 15, fontStyle: "italic", lineHeight: 22 },
  nextPhrase: { color: theme.colors.accent, fontSize: 13, fontWeight: "600" },
  accentCard: { backgroundColor: theme.colors.panel, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border, padding: 14, gap: 10 },
  accentHeader: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  accentFlag: { fontSize: 32 },
  accentInfo: { flex: 1, gap: 2 },
  accentName: { color: theme.colors.text, fontWeight: "700", fontSize: 15 },
  accentDesc: { color: theme.colors.muted, fontSize: 12, lineHeight: 17 },
  accentScore: { fontSize: 18, fontWeight: "700", minWidth: 40, textAlign: "right" },
  progressTrack: { height: 6, backgroundColor: theme.colors.border, borderRadius: 3, overflow: "hidden" },
  progressFill: { height: 6, borderRadius: 3 },
  accentActions: { flexDirection: "row", gap: 10 },
  listenBtn: { flex: 1, backgroundColor: theme.colors.accentAlt, borderRadius: 10, paddingVertical: 9, alignItems: "center" },
  listenBtnActive: { opacity: 0.7 },
  listenBtnDisabled: { opacity: 0.45 },
  listenBtnText: { color: theme.colors.text, fontWeight: "700", fontSize: 13 },
  autoStatusPill: { flex: 1, backgroundColor: "#eceff1", borderRadius: 10, paddingVertical: 9, alignItems: "center" },
  autoStatusPillPending: { backgroundColor: "#fff8e1" },
  autoStatusPillDone: { backgroundColor: "#e8f5e9" },
  autoStatusText: { color: theme.colors.text, fontWeight: "700", fontSize: 12 },
  speakCard: { backgroundColor: theme.colors.panel, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.border, padding: 14, gap: 10 },
  speakTitle: { color: theme.colors.text, fontWeight: "700", fontSize: 16 },
  speakHelper: { color: theme.colors.muted, fontSize: 13, lineHeight: 19 },
  shadowHint: { color: "#8a6d3b", fontSize: 12, lineHeight: 17 },
  modeRow: { flexDirection: "row", gap: 8 },
  modeBtn: { flex: 1, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, backgroundColor: theme.colors.background, paddingVertical: 9, alignItems: "center" },
  modeBtnActive: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
  modeBtnText: { color: theme.colors.muted, fontWeight: "700", fontSize: 13 },
  modeBtnTextActive: { color: "#fff" },
  textInput: { minHeight: 120, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, color: theme.colors.text, backgroundColor: theme.colors.background, fontSize: 15, lineHeight: 21 },
  customAccentRow: { flexDirection: "row", gap: 8 },
  customAccentBtn: { flex: 1, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, paddingVertical: 8, gap: 2, backgroundColor: theme.colors.background },
  customAccentBtnActive: { borderColor: theme.colors.accent, backgroundColor: "rgba(36, 99, 235, 0.12)" },
  customAccentFlag: { fontSize: 20 },
  customAccentText: { color: theme.colors.muted, fontWeight: "700", fontSize: 12 },
  customAccentTextActive: { color: theme.colors.text },
  speakBtn: { backgroundColor: theme.colors.accent, borderRadius: 12, paddingVertical: 12, alignItems: "center" },
  speakBtnDisabled: { opacity: 0.5 },
  speakBtnText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  shadowCard: { backgroundColor: theme.colors.background, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, padding: 12, gap: 8 },
  shadowActions: { flexDirection: "row", gap: 8 },
  shadowActionBtn: { flex: 1, borderRadius: 10, backgroundColor: theme.colors.panel, borderWidth: 1, borderColor: theme.colors.border, paddingVertical: 9, alignItems: "center" },
  shadowActionText: { color: theme.colors.text, fontWeight: "700", fontSize: 12 },
  recordBtn: { backgroundColor: theme.colors.accentAlt, borderRadius: 12, paddingVertical: 12, alignItems: "center" },
  recordBtnActive: { backgroundColor: "#b91c1c" },
  recordBtnText: { color: theme.colors.text, fontWeight: "700", fontSize: 14 },
  speakAccentInfo: { color: theme.colors.muted, fontSize: 12 },
  routineCard: { backgroundColor: theme.colors.background, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, padding: 12, gap: 10 },
  routineHeaderRow: { flexDirection: "row", justifyContent: "space-between", gap: 10, alignItems: "flex-start" },
  routineHeaderTextWrap: { flex: 1, gap: 4 },
  routineBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: "rgba(36, 99, 235, 0.12)", borderWidth: 1, borderColor: "rgba(36, 99, 235, 0.28)" },
  routineBadgeText: { color: theme.colors.accent, fontSize: 11, fontWeight: "800" },
  routineProgressTrack: { height: 8, borderRadius: 999, backgroundColor: "#dbeafe", overflow: "hidden" },
  routineProgressFill: { height: "100%", borderRadius: 999, backgroundColor: "#2563eb" },
  routineTitle: { color: theme.colors.text, fontWeight: "700", fontSize: 13 },
  routineHelper: { color: theme.colors.muted, fontSize: 12, lineHeight: 17 },
  routineStepText: { color: theme.colors.accent, fontSize: 12, fontWeight: "700" },
  routineStageRow: { flexDirection: "row", gap: 6 },
  routineStageChip: { flex: 1, borderRadius: 999, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.panel, paddingVertical: 6, alignItems: "center" },
  routineStageChipActive: { borderColor: theme.colors.accent, backgroundColor: "rgba(36, 99, 235, 0.12)" },
  routineStageText: { color: theme.colors.muted, fontWeight: "700", fontSize: 11 },
  routineStageTextActive: { color: theme.colors.accent },
  routineStepCard: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, backgroundColor: theme.colors.panel, padding: 10, gap: 8 },
  routineStepLabel: { color: theme.colors.text, fontWeight: "700", fontSize: 12 },
  routineCurrentWord: { color: theme.colors.text, fontSize: 18, fontWeight: "800", textTransform: "lowercase" },
  routineProgress: { color: theme.colors.muted, fontSize: 11 },
  routineMetric: { color: theme.colors.text, fontSize: 12, fontWeight: "600" },
  routineRewardRow: { flexDirection: "row", gap: 8 },
  routineRewardCard: { flex: 1, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, paddingVertical: 8, paddingHorizontal: 6, backgroundColor: theme.colors.background, alignItems: "center", gap: 2 },
  routineRewardLabel: { color: theme.colors.muted, fontSize: 10, fontWeight: "700", textTransform: "uppercase" },
  routineRewardValue: { color: theme.colors.text, fontSize: 16, fontWeight: "800" },
  routineResultRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 3 },
  routineResultWord: { color: theme.colors.text, fontSize: 13, fontWeight: "700", textTransform: "lowercase" },
  routineResultLabel: { fontSize: 12, fontWeight: "600" },
  routineWordChip: { borderRadius: 10, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.panel, paddingHorizontal: 10, paddingVertical: 7, minWidth: 86 },
  routineWordText: { color: theme.colors.text, fontWeight: "700", fontSize: 12 },
  routineWordMeta: { color: theme.colors.muted, fontSize: 10 },
  speakFootnote: { color: theme.colors.muted, fontSize: 12, lineHeight: 18 },
  assessmentError: { color: "#b00020", fontSize: 13 },
  assessmentCard: { backgroundColor: theme.colors.background, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.border, padding: 12, gap: 10 },
  assessmentHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  assessmentTitle: { color: theme.colors.text, fontWeight: "700", fontSize: 15 },
  assessmentScore: { fontWeight: "800", fontSize: 20 },
  assessmentSummary: { color: theme.colors.text, fontSize: 13, lineHeight: 19 },
  assessmentSection: { gap: 4 },
  assessmentLabel: { color: theme.colors.muted, fontSize: 12, fontWeight: "700" },
  assessmentTranscript: { color: theme.colors.text, fontSize: 14, fontStyle: "italic", lineHeight: 20 },
  wordGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  wordChip: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, borderWidth: 1 },
  wordChipMatch: { backgroundColor: "#e8f5e9", borderColor: "#4caf50" },
  wordChipMiss: { backgroundColor: "#ffebee", borderColor: "#f44336" },
  wordChipText: { fontSize: 12, fontWeight: "700" },
  wordChipTextMatch: { color: "#1b5e20" },
  wordChipTextMiss: { color: "#b71c1c" },
  wordRetryChip: { borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.panel },
  wordRetryChipActive: { borderColor: theme.colors.accent, backgroundColor: "rgba(36, 99, 235, 0.12)" },
  wordRetryText: { color: theme.colors.text, fontWeight: "700", fontSize: 12 },
  wordRetryTextActive: { color: theme.colors.accent },
  wordResultCard: { borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, padding: 10, backgroundColor: theme.colors.panel, gap: 4 },
  wordResultTitle: { color: theme.colors.text, fontSize: 13, fontWeight: "700" },
  wordResultText: { color: theme.colors.muted, fontSize: 12 },
  wordLegend: { color: theme.colors.muted, fontSize: 11 },
  assessmentBullet: { color: theme.colors.text, fontSize: 13, lineHeight: 19 },
  assessmentTip: { color: theme.colors.text, fontSize: 13, lineHeight: 19 },
});
