import { StyleSheet } from "react-native";
import { theme } from "../ui/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    padding: 20,
    gap: 14,
    paddingBottom: 40,
  },
  centered: {
    flex: 1,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  emptyIcon: { fontSize: 48 },
  emptyText: { color: theme.colors.muted, fontSize: 16 },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: theme.colors.text,
    marginTop: 12,
  },
  card: {
    backgroundColor: theme.colors.panel,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 14,
    gap: 10,
  },
  objective: {
    color: theme.colors.text,
    fontWeight: "700",
    fontSize: 15,
    lineHeight: 22,
  },
  badges: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  badge: {
    backgroundColor: "#ddeef2",
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  badgeAccent: {
    backgroundColor: "#fde8c2",
  },
  badgeText: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: "600",
  },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressLabel: { color: theme.colors.muted, fontSize: 13 },
  progressPct: { color: theme.colors.accent, fontSize: 13, fontWeight: "700" },
  progressTrack: {
    height: 8,
    backgroundColor: theme.colors.border,
    borderRadius: 4,
    overflow: "hidden",
    marginTop: -8,
  },
  progressFill: {
    height: 8,
    backgroundColor: theme.colors.accent,
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.colors.accent,
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    flexShrink: 0,
  },
  checkboxDone: {
    backgroundColor: theme.colors.accent,
    borderColor: theme.colors.accent,
  },
  checkmark: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  checkText: {
    color: theme.colors.text,
    fontSize: 14,
    lineHeight: 22,
    flex: 1,
  },
  checkTextDone: {
    color: theme.colors.muted,
    textDecorationLine: "line-through",
  },
  weaknessRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  severityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#e05a00",
    flexShrink: 0,
  },
  weaknessText: {
    color: theme.colors.text,
    fontSize: 13,
    flex: 1,
  },
  successCard: {
    backgroundColor: "#e8f5e9",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#a5d6a7",
  },
  successText: {
    color: "#2e7d32",
    fontWeight: "700",
    fontSize: 16,
  },
  resetLink: {
    color: theme.colors.accent,
    fontSize: 14,
    textDecorationLine: "underline",
  },
  button: {
    backgroundColor: theme.colors.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },

  // ── Exercise runner ────────────────────────────────────────
  exerciseStartBtn: {
    backgroundColor: theme.colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 10,
  },
  exerciseCounter: {
    fontSize: 12,
    color: theme.colors.muted,
    marginBottom: 6,
  },
  exerciseQuestion: {
    fontSize: 16,
    fontWeight: "600",
    color: theme.colors.text,
    marginBottom: 14,
    lineHeight: 22,
  },
  exerciseHint: {
    fontSize: 13,
    color: theme.colors.muted,
    fontStyle: "italic",
    marginBottom: 8,
  },
  optionBtn: {
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
    backgroundColor: theme.colors.panel,
  },
  optionBtnSelected: {
    borderColor: theme.colors.accent,
    backgroundColor: theme.colors.accent + "18",
  },
  optionBtnCorrect: {
    borderColor: "#22c55e",
    backgroundColor: "#dcfce7",
  },
  optionBtnWrong: {
    borderColor: "#ef4444",
    backgroundColor: "#fee2e2",
  },
  optionBtnText: {
    fontSize: 14,
    color: theme.colors.text,
  },
  fillInput: {
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: theme.colors.text,
    backgroundColor: theme.colors.panel,
    marginBottom: 10,
  },
  submitBtn: {
    backgroundColor: theme.colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 4,
  },
  feedbackBox: {
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
    marginBottom: 8,
  },
  feedbackCorrect: {
    backgroundColor: "#dcfce7",
    borderColor: "#22c55e",
    borderWidth: 1,
  },
  feedbackWrong: {
    backgroundColor: "#fee2e2",
    borderColor: "#ef4444",
    borderWidth: 1,
  },
  feedbackText: {
    fontWeight: "700",
    fontSize: 14,
    color: theme.colors.text,
    marginBottom: 4,
  },
  feedbackExplanation: {
    fontSize: 13,
    color: theme.colors.text,
    lineHeight: 18,
  },
  nextBtn: {
    backgroundColor: theme.colors.accent,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  scoreCard: {
    alignItems: "center",
    paddingVertical: 24,
  },
  scoreTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.text,
    marginBottom: 8,
  },
  scoreValue: {
    fontSize: 40,
    fontWeight: "800",
    color: theme.colors.accent,
    marginBottom: 6,
  },
  scoreSubtitle: {
    fontSize: 14,
    color: theme.colors.muted,
  },
  loadingText: {
    textAlign: "center",
    marginTop: 8,
    fontSize: 13,
    color: theme.colors.muted,
  },
  errorText: {
    color: "#ef4444",
    fontSize: 13,
    marginBottom: 8,
  },
});
